config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  
  get 'welcome/index'
  root 'welcome#index'
  
  #for any routing error, this will redirect to the home page
  get '*path' => redirect('/') 
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :content, :string
  
  validates :name, :email, :content, presence: :true
  validates_format_of :email,
    with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i 
  validates :content, length: {maximum: 500}
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates :title, :content, presence: :true
  
  def self.created_descending
    all.order("created_at desc") 
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  validates :title, :description, presence: :true
  def self.created_descending
    all.order("created_at desc") 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      UserMailer.contact_email(@contact).deliver
      redirect_to root_path, notice: "Thank you for your message!"
    else
      render :new
    end
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]  #if not signed in it will not allow us to create posts
  
  def index
    @posts = Post.created_descending.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "Sweet you got it bro!"
    else
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Success!"
    else
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path
  end
  
  private
    def post_params
      #Permit slug for friendly id
      params.require(:post).permit(:title, :content, :slug)
    end
    
    def find_post
      #Post.friendly.find makes use of the friendly_id gem
      @post = Post.friendly.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]  #if not signed in it will not allow us to create projects
  
  def index
    @projects = Project.created_descending.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.create(project_params)
    if @project.save
      redirect_to project_path(@project), notice: "Success"
    else
      render :new
    end
  end 
  
  def show
  end
  
  def edit
  end
  
  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Success"
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end
  
  private
    def project_params
      params.require(:project).permit(:title, :description, :link, :slug)
    end
    
    def find_project
      @project = Project.friendly.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.order("created_at desc").limit(5)
    @projects = Project.all.order("created_at desc").limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def time_formatter(time)
    time.strftime("%A, %b %d")
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  
  def markdown(content)
    #renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: false)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/new.html.erb
<% provide(:title, "Contact Dean") %>

<h1 id="page-title">Contact Dean</h1>

<div class="form-wrapper">
  <% if @contact.errors.any? %>
    <h2><%= pluralize(@contact.errors.count, "error") %></h2>
    <% @contact.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <%= form_for(@contact) do |f| %>
    <%= f.label :name, "Name", class: "form-label" %>
    <%= f.text_field :name, class: "form-field" %><br />
    <%= f.label :email, "Email", class: "form-label" %>
    <%= f.text_field :email, class: "form-field" %><br />
    <%= f.label :content, "Content", class: "form-label" %>
    <%= f.text_area :content, class: "form-field" %><br />
    <div class="button-wrapper">
      <%= f.submit "Send", class: "submit-button" %>
    </div>
  <% end %>
</div>

app/views/layouts/_flash.html.erb
<% if notice %>
  <p class="flash notice">
    <%= notice %>
  </p>
<% elsif alert %>
  <p class="flash alert">
    <%= alert %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="main-footer" class="clearfix">
  <p class="copyright">Website by Dean Chuang</p>
  <nav>
    <%= link_to '<i class="fa fa-twitter"></i>'.html_safe, "https://twitter.com/deanchuang1", target: "_blank" %>
    <%= link_to '<i class="fa fa-facebook"></i>'.html_safe, "https://www.facebook.com/dean.chuang.7", target: "_blank" %>
    <%= link_to '<i class="fa fa-github"></i>'.html_safe, "https://github.com/bluekites", target: "_blank" %>
  </nav>
</footer>

app/views/layouts/_navbar.html.erb
<header id="main-navigation" class="clearfix">
  <%= link_to "Dean Chuang", root_path, class: "logo" %>
  <nav>
    <%= link_to "Blog", posts_path %>
    <%= link_to "Projects", projects_path %>
    <%= link_to "Contact", new_contact_path %>
    <% if user_signed_in? %>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>

<%= render 'layouts/flash' %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
  var disqus_config = function() {
    shortname = 'deanchuang';
    this.page.identifier = '<%= @post.id %>';
    this.page.title = '<%= @post.title %>';
    this.page.url = '<%= url_for([@post, {only_path: false}]) %>';
  };
/*

var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//deanchuang.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error") %></h2>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %><br/>
  <% end %>
  
  <%= f.label :title, class: "form-label" %>
  <%= f.text_field :title, class: "form-field" %> <br/>
  <%= f.label :content, "Article content", class: "form-label" %>
  <%= f.text_area :content, class: "form-field" %> <br />
  <div class="button-wrapper">
    <%= f.submit class: "submit-button" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>

<h1 id="page-title">Edit Post</h1>
<div class="form-wrapper">
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Dean's Blog") %>

<h1 id="page-title">Current Musings</h1>

<div id="posts-wrapper" class="small-wrapper">
  <% @posts.each do |post| %>
    <div class="post">
      <p class="date"><%= post.created_at.strftime('%A, %B %d')%></p>
      <h2><%= link_to post.title, post_path(post) %></h2> <br/>
      <hr>
    </div>
  <% end %>
  <%= will_paginate(@post) %>
</div>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>

<h1 id="page-title">New Post</h1>
<div class="form-wrapper">
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>

<div id="post-show" class="small-wrapper">
  <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
  <h1 class="post"><%= @post.title %></h1> <br/>
  <hr>
  <div id="content">
    <p><%= markdown(@post.content) %></p>
  </div>
  <hr>
  <% if user_signed_in? %>
    <div id="admin-links">
      <%= link_to "Edit", edit_post_path(@post) %>
      <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
  <% end %>
  <div id="share-box">
    <p>Share <%= @post.title %></p>
    <!-- code for modal twitter share box -->
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @deanchuang1 - url = <%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height = 500, top=200, left=300');void(0);">
      <i class="fa fa-twitter"></i></a>
    <!-- code for modal fb share box -->
    <a onclick="javascript:window.open('http://facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
  </div>
  <hr>
  <%= render 'disqus' %>
</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error") %></h2>
    <% @project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %><br/>
  <% end %>
  
  <%= f.label :title, class: "form-label" %>
  <%= f.text_field :title, class: "form-field" %> <br/>
  <%= f.label :description, "Project description", class: "form-label" %>
  <%= f.text_area :description, class: "form-field"%> <br/>
  <%= f.label :link, class: "form-label" %>
  <%= f.text_field :link, class: "form-field" %><br/>
  <div class="button-wrapper">
    <%= f.submit class: "submit-button" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% provide(:title, "Edit Project") %>

<h1 id="page-title">Edit Project</h1>
<div class="form-wrapper">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<% provide(:title, "Dean's Projects") %>

<h1 id="page-title">Recent Projects</h1>

<div id="posts-wrapper" class="small-wrapper">
  <% @projects.each do |project| %>
    <div class="post">
      <p class="date"><%= project.created_at.strftime('%A, %B %d')%></p>
      <h2><%= link_to project.title, project_path(project) %></h2> <br/>
      <hr>
    </div>
  <% end %>
  <%= will_paginate @project %>
</div>

app/views/projects/new.html.erb
<% provide(:title, "New Project") %>

<h1 id="page-title">New Project</h1>
<div class="form-wrapper">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.title) %>

<div id="post-show" class="small-wrapper">
  <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
  <h1 class="post"><%= @project.title %></h1> <br/>
  <hr>
  <div id="content">
    <p><%= markdown(@project.description) %></p><br/>
    <div class="button-wrapper">
      <%= link_to "Visit #{@project.title}", @project.link, class:"project-button", target:"_blank" %> 
    </div>  
  </div>
  <br/>
  <hr>
  <% if user_signed_in? %>
    <div id="admin-links">
      <%= link_to "Edit", edit_project_path(@project) %>
      <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<% provide(:title, "Dean Chuang | Web Developer") %>

<div class="wrapper clearfix">
  <div class="col-1 homepage-content">
    <h2>About Dean</h2>
    <hr>
    <p>
      I'm a web developer with a knack for Full-stack development. My main goal is to create functional, beautiful, and elegant products.
    </p>
    <p>
      Originally coming from a Biological Sciences background, I later realized that programming is my true passion.  I then enrolled in the Thinkful Frontend Career Path with Pragmatic Studios as a supplement in order to learn the ins and outs of web development through industry experts. 
    </p>
    <p>
      With a solid foundation for front and back end development, I am currently working to advance my knowledge in React and Node/Express. 
    </p>
  </div>
  <div class="col-2 homepage-content">
    <h2>My Current Musings</h2>
    <hr>
    <% @posts.each do |post| %>
      <h3><%= link_to post.title, post %></h3>
      <p class="date"><%= time_formatter(post.created_at) %></p>
    <% end %>
  </div>
  <div class="col-3 homepage-content">
    <h2>My Recent Projects</h2>
    <hr>
    <% @projects.each do |project| %>
      <h3><%= link_to project.title, project %></h3>
      <p class="date"><%= time_formatter(project.created_at) %></p>
    <% end %>
  </div>
</div>